project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Everything"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers/index.qmd
        text: Research
      - href: notes/index.qmd
        text: Study
      - href: blog/index.qmd
        text: Blog
  search: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    html-math-method: katex

bibliography: references.bib